name: semantic
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - cpuonly=1.0
  - pytorch=1.8.1
  - transformers=4.6.0
  - faiss-cpu=1.7.0
  - flask=1.1.2
  - flask-restful=0.3.8
  - marshmallow=3.12.1
  - python-dotenv=0.17.1
  - gunicorn=20.1.0
  - pip=21.0.1
  - pip:
      - sentence-transformers==1.1.1
      - protobuf==3.17.0
